---
title: "Module 13: Business Analysis, Risk Identification and Initial Assessment"
author: "C. Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Module Objective

Discuss the framework for risk management and control within a company

* Discuss the cultural aspects of risk assessment and management including the problems of bias

Discuss the application of the risk management control cycle

* Relevane of external influences and emerging risks

Discuss how to identify risks and their causes and implication

Explain what is meant by risk and uncertainty and discuss different definitions and concepts of risk

***

ERM invovles all risks faced by an organization

First need to determine and understand what risks the org. face

* Process of risk identification (incl. considerations of why each risk arises and an initial assessment of the impact it could have on the org.)

Module focus on the first party of the risk management control cycle

1. **Business analysis**:  
Need to understand and know the specific characteristics of the org. and its operating environment before risk can be identifided comprehensively
2. **Risk identification**:  
Systematic process to identify the risks to which the org. is exposed
3. **Initial assessment of risk**:  
Initial evaluation of the risks (quant. & qual.) to facilitateprioritiztion of appropriate risk management actions

Will discuss how to implement, methods and outputs of the process as well as the issues invovled in identifying emerging risks and the problem of bias

(Again, this only covers upto the initial assessment)

Note: language on identification, assessment, evaluation, quantification can be use as being distinct or overlap in meaning

## Risk Identification and Assessment Process

6 steps of a comprehensive risk identification and initial assessment process

***1. Business analysis***

Ensure that the company has clear business objectives  
(Or lese difficult to establish what risks can impact on their achievement)

Analyse its operation and its wider environment

* Business plan
* Company's structure and system of internal controls
* Current and projected accounts and accounting ratios
* Market information (e.g. competitors actions and market share)
* Resources available to the company
* Legislative and regulatory constraints
* General economic environment

***2. Identify the risks***

Identify up & down side risk structurally

Start with a review of the findings of the business analysis to identify any areas or risk, uncertainty or opportunity

See next section for risk identification methods

***3. Obtain agreement***

Obtain agreement (with other stakeholders?) on the risks faced, relationships between them, and identify individuals who will be responsible for each risk and its management

***4. Evaluate the risks***

Evaluate in terms of **likelihood** and **severity**

* e.g. probability of occurence within a year and financial or reputational impact

Can be done for both gross and net of existing controls

Enable risks to be prioritzed for further implementation of controls

***5. Produce a risk register***

Record the results of this process in one place

Next section will further discuss elements of the register

***6. Review the risk register regularly***

Espeically in times of change to ensure that it remains up to date and reflects the current risks faced by the company

### Benefits of the Process

This is an important first step in the RM process

* Enhances awaremness and transparency of risks
* Helps transfer knowledge and improve understanding across the org.
* Acts as a firm base for subsequent risk analysis, quantification and prioritization
* Enhances the quality of reporting to the Board and senior management
* $\therefore$ Helps improves business decision making

### Requirements

Requirements to gain the benefits above:

* Need senior sponsorship of the RM program
* Be consistent on the standards used overtime
* Ensure quantitative and qualitative data is used so as to develop a comprehensive risk profile for the whole org.
* Integrate risk identification with the entire RM process
* Demonstrate added value (on top of meeting regulatory requirements)

### Risk Assessment Process

4 stage risk identification and assessment process (expansion of step 2 above)

***1. Foundation setting***

* Get executive sponsorship
* Organize and plan for resources  
(e.g accountabilities and deadlines)
* Define a risk taxonomy
* Build a customized risk identification and assessment tool (see Sec. 2)
* Educate and train project teams and management

Potential pitfall:

* Lack of senior management buy-in and participation
* Bad resources planning and alloaction
* Insufficient preparation lead to an inefficient or ineffective process
    
***2. Risk identification, assessment and prioritization***

* Understand business objective, risk appetite, regulatory and policy requirements
* Undertake risk assessments; top down (e.g. interviews) and bottome-up (e.g. workshops)
* Produce risk reports and risk maps (Sec 3)
* Prioritize risk

Potential pitfall:

* Lack of clear business objectives or risk appetite
* Focusing on consequences rather than causes of risk
* Inconsistent estimate of frequency and severity

***3. Deep dives, risk quantification and managment***

* Detailed assessments of of the top risks (prioritized from step 2.)
* Produce risk tolerance statements and track KRIs
* Determine risk management strategies and the total cost of risk (for pricing purpose)

Potential pitfall:

* Lack of prioritization of key risk
* Insufficient risk quantification
* Risk assessment not translated into value adding action

***4. Business and EMR integration***

* Link risk assessment with both strategic planning and business review processes
* Integrate risk assessment into everyday business operations (e.g. pricing and capital allocation)
* Conduct scenario analysis and stress testing
* Report on risk
* Creating and maintaining loss/events databases
* Establish appropriate risk-escalation policies

Potential pitfall:

* Restricting integration to low level reports
* Failure to fundamentally change the business attitude to RM

***

See Lam App to Ch.23 with the risk assessment self eval checklist
;
* How well developed and mature their risk identification and assessment is
* Degree of integration of RM across the org.

## Risk Identification and Recording

### Risk Identification Tools

***SWOT Analysis***

Framework for generating ideas in a structured and comprehensive ways

Consider strengths, weakness, opportunities, and threats

Use to establish what risks the company faces

***Risk Checklist***

List of risk identified in the past or from external source

Need to make sure the information is relevant and up to date

***Risk Prompt List***

List of different categories of risk to consder and examples of each

* Can be produced at an industry wide level

Similar to risk trigger questions

List situations and events that have previously emergerd and that should be considered

e.g. PEST(ELI) analysis that covers political, economic, social, technology (environmental, legal and industry) risks

***Risk Taxonomy***

Structured way of classifying risks and breaking them down into components

help to ensure that those involved in the process have a common understanding of the terms used in risk identification

Less project specific than a checklist and less industry specific than an industry prompt list

***Case Studies***

Can help to understand th eimpact of risks in a specific context

***Process Analysis***

Build flow charts that detail business process and links between them

Help identify the risks that arise at each stage

Particularly suited to op-risk

***

Advantages of the tools above:

* Provide a clear structure for the risk identification process
* Improve the quanlity of the output (vs a less structured process)

Disadvantage of the tools above:

* Results may still not be comprehensive (e.g. due to bias in the process or the participants)

### Risk Identification Techniques