---
title: "Module 11: Stakeholders"
author: "C. Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Module Objective

Understand the relevance of ERM to all stakeholders

* Discuss the relevance of risk measurement and management to all stakeholders
* Discuss the risk arising from any misalignment of interests between different groups of stakeholders

***

Consider the **objectives** of various `stakeholders` and their **interest in ERM**

* Also consider how these **interest may conflict**

This module covers different areas relating to the implementation of the ERM process within an org., including an understanding of the wide range of stakeholders to whom ERM is relevant and issues arising from this

***Exam note:***

* For any given scenario, needs to be able to **identify** the **main stakeholders** and discuss their **roles**

* Need to be able to analyze a scenario from the **RM perspective of a specified stakeholder**

* **Compare** and **contrast** this with the RM perspective of another class of stakeholder

## Stakeholders

There is typically a wide range of stakeholders for whom risk measurement and management is highly relevant

***Stakeholder***:  
Someone who **supports** and **participates** in the **survival** and **success** of a company

* Stakeholders nowadayws requires more risk transparency

* Stakeholders can be *categorized* based on their **relationship to the company**

| Category  | Relationship                               | Example |
| --------- | ----------------------| ---------------------|
| **Principal** | Contribute capital and/or expect a return  | `Shareholders`; `debt-holders`; `customers`; `government`; `insurance market`; `financial market` |
| **Agency**    | Paid by principals to perform a specific role on their behalf | `Company directors`; `pension scheme` trustees and administrators; `company managers`; `employees`; `auditors`; `investment managers` | 
| **Controlling** | Supervise the principals or their agents | `Professional bodies`, `regulators`, `industry bodies`, `government` |
| **Advisory** | Advise the principal or their agents | `Actuaries`; `lawyers`; `credit rating agencies`; `investment advisers`; `shareholder service providers` |
| **Incidental** | Affected by the behavior and actions of the principal or their agents | `Creditors`; `suppliers`; `other business partners`; `general public`; `media` |

### Shareholders

***Characteristics and Roles***:

* **Seek a good return** on their investment (dividends and share value) taking into account the inherent degree of risk
  
    * Strong interest in protecting against serious downside  
    (e.g. any events that could cause a collapse in the share price)
  
    * Equally may seek value creation through risk-taking
  
    * May prefer `short term` gain (public s/h) or `long term` investment (private s/h)

* **Relies** on `directors` and `auditors` to safeguard their investment (except)

* Have **limited power** (unless majority holding) until problems become significant

***Shareholder service providers / proxy advisors***

* Act on behalf of shareholders

* Express considered views on the company  
(e.g. `corporate governance`, `Board composition`, `remuneration`)

* (*optionally*) manage their **proxy voting**

***Benefits***: 

* Shareholder becomes **more influential** and vocal on controversial issues when they subcontract their responsibilities to such organization

***Concerns*** on the role of proxy advisers:

* Power but **no responsibility**: 

    They can influence a high proportion of voting rights but have no interest in the outcome of the vote
    
* Potential for **conflict of interest**:  

    Some firms provide consulting and other services to the companies on which they are making voting recommendations
    
* **"Tick-box" (quantitative) methodology**: 

    Common template is applied to all firms with little considerations being given to qualitative aspects of the individual circumstances of each company being assessed

### Customers and Policyholders

***Characteristics and Roles:***

* Seek both **good value** for money and **security** of the company

*  Very **weak individually**

    * *Collectively* can have greater power especially when supported by consumer advocacy groups

* Have different **perspectives depending on the type** of org.

    * `Bank customers` risk appetite $\approx$ **debtholders**

    * `Building society account holders` risk appetite $\approx$ shareholders

    * `Insurance company p/h`: `pure customers` or `shareholders` (mutual company)
    
#### Aspects of Customer Management

***Acquiring*** and ***retaining*** customers

* Can increase value by improvements in *attracting* and *retaining* the **right customers**

* Retention is particularly important as it is cheaper to retain

    * Company in *practice* have **high customer turnover**
  
    * **Long term customers** are particularly valuable:

        * Tend to **purchase larger quantities**
        
        * **Less price sensitive**
        
        * More **likely to recommend** the company

**Retaining** customer ***loyalty***

* Dissatisfied customers: 

    * Will leave
    
    * Might dissuade potential customers from purchasing

* Need to perform sufficiently well to retain the customer's loyalty  
(i.e. continues to purchase from the company)

    * Not sufficient to merely satisfy a customer

***Knowing*** your customer

* Customer surveys, feedback and data mining

* Keep in mind of customer privacy

Effective ***crisis management***

* Crisis generally **damages reputation unless handled well**  
(with might actually enhance it)

* Company should have **contingency plans** in place before a crisis occurs

* When a crisis strikes:

    * Should **be honest**; do not try to cover it up
    
    * **Act swiftly** and resolve it
    
    * **Keep stakeholders informed**
    
    * **Focus on the long-term** future of the business rather than minimizing short term cost

### Directors

***Characteristics and Roles***:

* Need to **balance** the **needs of other stakeholders** and their own **personal goals**  
(Which may be influenced by the form of remuneration)

    * NED can conflict with shareholders with things such as need to maintain their directorship and remuneration

* Have significant **duty of care** in terms of *risk management*

* Need to fully **understand the business**

* *Able* and *willing* to **challenge management decisions**

* Need to ensure that the **company remains compliant** with all relevant **regulation**

* Risk perspectives $\approx$ `shareholders`  
(since they are shareholder's agents)

    * Additional responsibility:  
    Determining the **value** of the `assets` and `liabilities` of the company

* **NED**:  
Responsible *purely* for **safeguarding the interests of shareholders**

* **ED**:  
**Hold roles within the firm** and can be considered to an extend as **employees**

    * ED risk perspectives $\approx$ `employees`  
(since they are employees)

### Employees

***Characteristics and Roles***:

* Should be part of the **day-to-day ERM process** (not just ERM and IA)

* Seek **Job security** and **benefits**

    * Directly related to the **profitability** and **security** of the **company**
    
* Part of the **company's op-risk**  
(e.g. management and retention of staff and their inherent expertise)

    * Employees with higher levels of **agency risk**

        * **Low level** employees
        
        * **Members of unions**
        
              (They may organize strikes, demand standardized wage arrangements and can influence employee's morale)
              
        * **Free agents**

#### Aspects of Employee Management

3 **key aspects** of employee management and the **potential effects** of each

1. ***Recruitment***

    * Companies need to identify and recruit the right individuals
      
    * `Cash compensation`, `incentives` and `benefits` are important

2. ***Retention, promotion and training***

    * **Turnover can be costly**: Skills and knowledge are lost (or strengthen a competitor)
      
    * **Career development programmes** and **continual training**: Can improve `employee morale`, `retention` and `productivity`
      
    * Important that employees **feel valued** and that their **achievements are recognized**

3. ***Dismissal and resignations***

    * **Large scale redundancies**:
    
        * Adversely **affect morale**
        
        * Can lead to **voluntary resignations** by other  
        (perhaps highly value employees)
      
    * **Managed programme of dismissals** (up or out) can increase employee motivation
      
    * **Exit interviews** are good ways to find out why employees are leaving and can address these issues for the future

***Key groups*** of employees to **align their interest with shareholders**

* Central risk function and CRO

    Assess the level of risk across the org. and enforce risk management policies)

* **Pricing** teams

    Instrumental in ensuring the profitability of the company

Important to align their interests with those of the shareholders through proportionate rewards for taking appropriate risk

### Regulators

***Characteristics and Roles***:

* Ensure **compliance** with the relevant regulatory standards

* Protect the **stability of markets**

* **Balance is key**

    Needs to be **sufficient controls** to protect `other stakeholders` (customers and p/h) 
      
    Can not be so restrictive that the market is constrained and can not **operate freely and efficiently**

* Need appropriate **intervention process**

    To ensures that issues are dealt with in good time but also allows opportunity for correction and improvement (avoid closing down operations unnecessarily)

* More details in Module 5

***Post 2008 Regulatory/Superivsory Change***

* Much greater interest in companies' `RM practices` and `capital requirements`

* `Stress tests` have become more stringent

* Companies are subjected to **more regulation from **multiple sources**  
(e.g. gov and stock exchange)

    $\therefore$ Boards are more actively involved in the oversight of risk (esp. strategic risk)

* Updated SEC disclosure requirements

* Temporary bans on short-selling

* **Dodd Frank**
    
    * **New regulators**: Consumer Financial Protection Bureau in US
    
    * Requirements for banks to have an **orderly liquidation plan**

* Replacement of the FSA with **PRA and FCA** in UK (See module 5)

* Greater likelihood that a company's `regulatory capital` requirement will *exceed* those determined by their own `internal model`

### Government

***Characteristics and Roles***:

* *Set* **regulations** and **legislation**

* **Intervene** when companies get into trouble
    
    * **Lender of last resort**
    
    * **Nationalization of a company** that would otherwise fail

***4 key risks faced by governments***

1. Insufficient tax revenues

2. Inappropriate insolvencies  
(failure of strategically important org. lead to contagion risk)

3. Regulatory arbitrage

4. Electoral losses

### Professional Advisors

***Characteristics and Roles***:

* **External auditors**
  
    * Perform **annual reviews** of accounts
  
    * *Assessments* of the **inherent risks** and the ways in which those risks are being managed
  
        * Effectiveness depend on the degree of disclosures and the extent to which issues are hidden by the management of a company

  * **Duty to report openly and honestly** on the state of the company on behalf of shareholders and regulators

* **Other professional advisers**
  
    * **Request from management** to *investigate* and *report* on specific matters  
    (e.g. provide assurance or otherwise to the various stakeholders)
    
    * Bring **independent technical expertise** and industry **bench-marking information**
    
    * Management doesn't have to act on their findings

***3 risk faced by professional advisers***:

1. **Reputational** risk

2. Risk of **litigation**

3. **Conflict of interest**  
(e.g. same accounting firm providing both audit services and consulting services to the same client)

### Credit Rating Agencies

***Characteristics and Roles***:

* Act as **gatekeepers** to companies wishing to **raise capital**

* Strong **influence** on `share price` and can influence the `view of external observers`

* Nowadays place much **greater emphasis on risk management**

* **Conflict of interest**: Needing to protect `reputation` and the way their `income` is generated

***2 risk faced by credit rating agencies***

1. Reputational risk

2. Conflict of interest

### Creditors

***Characteristics and Roles***:

* **Require repayment** of the money owe to them

* Mostly *interest* in the **security of the company** over the repayment term
  
    * Not concern about specific risks as long as debt are paid

* In difficulty, might waive interest payments in order to secure repayment of part of the capital

***Key risk for bondholders***

* Depends on debt **seniority**, presence of **security** or **covenants**

* Private debt (e.g. bank facility) is less liquid and more risky

* Debt finance choice considerations

    * **Taxation** (interest being tax deductible)

    * Risk of **insolvency**

    * **Agency cost**
    
***Trade creditors risk***

* **Lack of power** to have their debt repaid

### Subcontractors and Suppliers

***Characteristics and Roles***:

* *Affect directly* by the **failure** of a `company` or its `processes`
    
    * Both in respect of **future income** and being **potential creditors**

* Companies themselves are exposed to the **risk of failure** of `subcontractors` and `suppliers` (esp. when cost of replacement is high)

### Trustees and Beneficiaries of the Pension Scheme

***Characteristics and Roles***:

* Demand **security of the pension scheme** (dependent on the overall financial security of the sponsoring company)

* Need to *balance* **scheme security** with the **cost of benefit provision**

    e.g. Can choose to close a weak scheme rather than increase contributions  
    (Might not be in the best interest of active members)

Risk perspectives of ***DC scheme members***

* = policyholder or investor

* $\approx$ creditors  
(e.g. if employer's contribution are unpaid)

Risk perspectives of ***DB scheme members***

* $\approx$ debtholders or customers
* Scheme sponsor's perspective = equity provider 

    They benefit from any surplus but may need to provide additional funds

Risk perspectives of ***scheme trustees***

* = members (as they are member agents)

* May have **conflict of interest** depending on their other relationships to the scheme

### General Public

***Characteristics and Roles***:

* Interest through being most of the above  

    `S/h`, `bond/h`, `employees`, `pension scheme members`, `existing/future customers`, `taxpayers` or the `dependents` of any of these stakeholders

* **Assessment** of `the org.` and `risk events` is heavily **influenced by the way they are reported**

    * Speed and geographical spread of the distribution of information has increased from internet and related technologies

    * In can be debate that media have a duty to ensure that reporting is responsible and in the public interest

        **Irresponsible reporting** can exacerbate the reaction of those with limited access to other information or with limited expertise and can **escalate the problems**

### Business Partnerships

***Benfits of a strategic alliance***:

* **Faster** product development

* **Access** to new markets

* ••Sharing** of financial **risks**

* Benefit from **economies of scale**

**Potential pitfall** of a strategic alliance:

* **Conflicts of interest**

* **Waste** of *resources*

* *Damage* to **reputation**

* *Loss of* `intellectual capital` or *disputes* over `intellectual property`

Ways to ***maximize chance of success***

1. Only form an alliance if it really is the best options

    * Only to **meet a specific goal** that can best be met through an alliance

    * Best if **significant control is required** but a full merger is unnecessary

2. Find the right alliance partner

    * Need a decision making team and should reach **agreement on the goals** of the alliance

    * Should develop a set of **evaluation criteria** against which potential partners can be evaluated and a **ranked** list of potential partners

    * **Entire team** should meet and grade each potential partner

3. **Monitoring the progress** of the alliance carefully

    * Standard financial measure may not be appropriate initially  
    (e.g. Focus on quality of work etc)

    * Alliance should have **sufficient resources** and **low staff turnover**

    * Work of the alliance may need to be **reviewed and refocused regularly**

## Conflicts between Stakeholders

Conflict between stakeholders will arise **due to different objectives**

* Companies should develop a clear **understanding of each stakeholder's interest**

* Interests should be **aligned where possible**, with this information recorded and disseminated amongst the stakeholders

* Stakeholder `interest` and `requirements` should be **reflected in the corporate business plan**

### Agency Risk

Board runs the business for the benefit of the owners (e.g. s/h)

***Benefits*** of **separation of management and ownership** 

* Have those with expertise in running a business to have decision making responsibilities without investing capital

* Investors can invest without getting involved with day-to-day running of the company

* **Continuity of management** despite frequent change in owners

***Agency risk***:  
When **interest** of the `owner` and `agent` are **not fully aligned**, the agent may not always act in the interest of owners

* Similar concept: `problem of agency`, `principal-agent problem`, `agency dilemma`

* Difficulties that arise under conditions of **incomplete and asymmetric information** when a principal hires an agent

***Managers Remuneration***

* Managers may have **different interest** to shareholders

    * Can arise due to the way in which management team is compensated

    * Reward short term profits rather than long term investment

* Executive comp. is an important consideration

    * An end objective of an ERM framework:
    
        Ensuring that **compensation schemes** take into **account risk* in an appropriate manner

* e.g. Ibanker who are rewarded for good results yet the downside for poor performance is limited

***Situations*** where conflicts or agency risks may arise

* Remuneration of key employees

* Financing decisions

* Situations involving a dominant CEO

* Management decisions

***Agency Cost***:  
Cost arising from agency risk

* Can *include* **costs** associated with **mitigating** agency risk

    e.g. developing astute and robust remuneration and reward schemes;  
    monitoring the actions of others and seeking to influence their actions

* Include **actual losses** from these actions

### Remuneration of Key Employees

***Agency risk played a role in 2008 crisis***

* Underlying **misalignment of the interest** of `employees`, `management` and `shareholder` in banking

    Due to the **short term** and **asymmetric** nature of employee and management **reward structure**

    e.g. Employees were given bonuses based on the growth in the total amount loaned  
    $\therefore$ Curtailing lending can put loan officer's career at risk

    * Shareholder's interest for the bank was to only lend to fundamentally sound borrowers

* **Competitive forces** (such as one bank offering 100% mortgages) **exacerbating** the lending spiral and drove expansion into higher risk (sub prime) lending  
(e.g. US NINJA loan and UK 120% mortgages)

### Financing

***Conflict between providers of finance**

* Lenders (banks, bondholders) and the providers of equity capital (s/h)

* Difference between the lender's `short-term` **desire for security** and the s/h's `long term` **interest in the sound development** of the company

### Dominant CEO Risk

Risk that the CEO surrounds themselves with **"yes" people**

* Who try to win favor with the CEO irrespective of the risks that their decisions generate for shareholders and other stakeholders

* Can exist further down the hierarchy in the form of a very dominant manager or team leader

***Example***:

* `Equitable Life` and the `Mirror Group` (Module 32) and `Confederation Life`

* The latter collapsed in 1994 with losses estimated $1.3 bn after a high risk investment strategy set by its domineering Chairman

### Low-risk Management Decisions

Mangers try to ensure their personal **job security** by **making low risk investment decisions**

* Similarly penalize the company's long term profitability and the s/h return

* Manager may **resist M&A** that might threaten their own prospects

    * e.g. Yahoo's resist of takeover by MS in 2008

### Regulators and Government

Remuneration and career prospects of `regulator` and `politicians` may be **misaligned with the interest of the general public**

***Example***:

* Regulators **rewarded by financial crisis**:  

    Crisis typically lead to **greater regulation** and **higher remuneration** of regulators

* **Absence** of direct **penalties to regulators from failure** to regulate the market and market participants properly can result in dysfunction

* Can further **misalign** their interest with those of the `market` and the `general public`

Debate is on-going on the ***role of (lack of) regulation as a contributor to the global crisis***

* Can be argues that some UK regulators have been "punished" as the regulatory system is subsequently restructured

***Line of least resistence***

* Politician's inherent interest to get re-elected, they can aim to support policies that upset the least number of people in the short term rather than those that are the best long term solutions

* Pursuing the "line of lease resistance" rather than the "line of greatest advantage"