---
title: "Module 2: Why (E)RM?"
author: "C. Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Module Objective

Describe the concept of ERM:

* Describe the benefits of ERM

## Benefits of RM

**1. RM can benefit society**

* Modern Society relies on the banking and financial systems to operate smoothly
* Contagion risk

**2. RM is part of the job of management**

* The Board is supposed to optimise risk/return decisions for shareholders
* Investors/fund managers is several degrees away for effective risk management as it requires:
    * Historical data on risk/return results, volatilities and correlations
    * Risk exposure and concentration in the business
    * Future business and investment plan that may alter the firm's risk profile

**3. Reduce earnings volatility**

Predictable earnings:

* $\uparrow$ MV of firm (reduce risk of bankruptcy and tax liability)
* $\uparrow$ Company's credit rating
* $\downarrow$ Variability in employee costs (reduce swings in # of employees required)
* $\downarrow$ Capital requirements (less risk capital is needed)

**4. Maximize shareholder value**

Management can make better decisions given a better understandig of the risks the company faces $\Rightarrow$ $\downarrow$ cost of capital, $\uparrow$ risk/return trade off

* Better target investment returns and product pricing that reflects the underlying risks
* Appropriate capital allocation to achieve optimal risk-adjusted return
* Company has the appropriate skills to manage all of its risks to protect against large financial losses or damage to its reputation
* Perfromance metrics and incentives are aligned with the enterprise's business and risk objectives
* Key management decisions explicitly incorporate the element of risk

**5. Enhance job security and rewards**

* RM is a required competence for senior management
* Benefits employee with stock options

***

Risk appetite and risk profile

* Need a clear statement of risk appetite and profile to make decisions on which risk to accept or avoid
* Risk appetite = risk a company is willing to accept on an ongoing basis
* Risk profile = types of risks that a company faces and its current exposure to those risks

## Benefits of ERM

**1. Better Risk Reporting**

$\uparrow$ risk transparency $\Rightarrow$ management more informed $\Rightarrow$ improve business performance

ERM takes responsibility for risk reporting across the whole organization to ensure that *all risks* are reported in a *consistent* and appropriate format to stakeholders thereby $\uparrow$ *risk transparency*

* Provide timely and concise information on the company's key risks
* E.g. aggregate losses, policy exceptions, risk incidents, key exposures, early warning indicators etc

$\Downarrow$

ERM allows senior management to be more informed when making decisions due to:

* Better understanding of risk exposure
* Better comprehension of the links between growth, corporate risk and return
* Better understanding of the impact of $\Delta$-ing external factors (e.g. interest rate)
* More accureate accessment of a decisions's risk/return trade-offs
* Align strategy more closely with risk appetite

$\Downarrow$

Improve business performance

**2. Improve operational effectiveness**

* *Co-ordinating* risk management activities across all parts of the organization
    * E.g. corrdinate existing risk and oversight functions such as finance, audit/compliance and other specialist risk units
    * CRO can provide top down coordination
    * Centralization enable firms to react quickly to emerging risk
    * Prioritize various risks arising from various areas of an organization
* Encourage and facilitating the *sharing of risk information*
* Identifying and assessing *links* between risks managed by various teams
* Improving efficiency (w/ management time and business resources)
    * Cost savings from dealing with it firm wide
    * Or just natural hedge

**3. Enhance business performance**

ERM's support on key management decisions leads to:

* More efficient use and allocation of capital
* Minimize losses
* Early warning of risk
* Improve pricing, managing, transferring risks better
    * Achieving adequate risk-adjusted return
* Optimizing risk mitigation strategies (e.g. natural hedges between BUs)
* Reacting more quickly to opportunities (or risks)
* Gain value from RM by understanding the true risk/return economics of a business $\Rightarrow$ Take more of the profitable risks that make sense

**4. Integration Adds Value**

ERM requires integration:

* Integrated risk organization e.g. IRM that reports to the CEO and board
* Integration of risk transfer strategies to account for diversification/concentration
* Integration of risk management into the business processes of the company
    * ERM optimizes business performance by: supporting/inflencing pricing, resource allocation, etc
    * This is the stage where ERM is an offensive weapon

***

Risks faced by companies are highly interdependent $\Rightarrow$ Silo based RM is not efficient or effective

* Missing the interdependencies, associated risks maybe not be captured and the big picture maybe be overlooked
* Challenge of aggregating risk exposures across the organization

ERM has integrated analyses, strategies, and reporting $\Rightarrow$ Addresses interdependencies and aggregate expsoures

ERM supports the alignment of oversight functions (risk, audit, compliance) and rationalize risk assessment, risk mitigation, and reporting activities

ERM consider how macro factors impact the organization's risk/return profile

**System integration** allows for enterprise level data management, robust business and data analytics, straight through transaction processing, and more effective reporting and information sharing

Integration of **strategy** and risk allows a company's managment to better understand and challenge the underlying assumptions and risks associated with the business strategy

* Driver of market value declines are driven by strategic risks 60% of the time, op risk 30% of the time and then financial risks

## Reasons to Initiate ERM

Company usually pressured to implement ERM due to:

* Previous management failures
* Near miss
* High profile disaster in another organization
* Regulator/auditor criticism or demands
* Other influential stakeholders concerns (s/h, employees, rating agnecies, etc)

(Ask MS, what in MR triggers the initiation of ERM?)

Stakeholder's expectation of effective risk management practice due to increased in available tools to assess and manage risk

* e.g. VaR and RAROC to measure risk
* e.g. Credit derivatives and CAT bonds for risk risk transfer

## Case Study: How ERM Addes Value

Based on Lam Ch.21 case studies

* Investors will pay a premium for well governed companies
    * On the flip side, they would avoid companies with poor governance standards

Companies with strong governance structures:

* Sought after by investors at a premium (12-30%) and weak ones are avoided
* Tend to outperform (ROE) companies with weaker governance
* Lower volatility of returns, improved s/h value, financial stability, commands ~16% equity premium (For insurance companies)
* Perform better during stock market crashes (e.g. 2008, companies with excellent S&P EMR rating did better)

Effect is amplified for larger companies