---
title: "Module 3: How to do ERM - internal risk frameworks"
author: "C. Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Module Objective

Framework for RM and control

* Appropriate framework for ERM
    * Shows how strong governance and compliance practices can support ERM
* How to adopt best practice in ERM in compliance and corporate governance
* Cultural aspects of risk assessment and management including the problems of bias
    * Shows the importance of risk culture

Cover good practice in terms of framework, governance and culture (in detail)

Need to be able to evaluate the quality of these aspects with a hypothetical organization and to recommend an appropriate framework or improvements given specific circumstances

## Internal Risk Framework Components

Seven major components of ERM framework

1. Corporate goverence:  
Establish organizational processes and controls

2. Line management:  
Integrate risk management into business processes

3. Portfolio management:  
Aggregate risk exposures and identify diversification effects and concentrations of risk

4. Risk transfer:  
Mitigate excessive risk exposure cost effectively

5. Risk analytics:  
Measure, analyze and report on risk

6. Data and technology resources:  
Support the analytics and reporting

7. Stakeholder management:  
Communicate and report on risk

## Corporate Goverance

The same Board principles below applies to other bodies of governance roles e.g. Board of a mutual co. or the trustees of a pension scheme

**Corporate governance**:  
The way in which the Board controls the company and the processes that it puts in place to ensure that the company is being run by the management in the best interests of shareholders

**Board responsibilities** with regard to risk management

Risk governance:

* Setting the vision, strategy and risk culture of the organization
* Establishing a framework for measuring, managing and monitoring the risks facing the organization
* Reviewing the outcomes of and lessons learnt from the risk management process on an ongoing basis to achieve its goal of delivering long-term value to is investors

Setting ERM policies:

* Defining the company's risk appetite
* Establishing what skills are needed to implement ERM strategies successfully, and implementing training programmes where these skills are deficient
* Guiding decisions on the most appropriate approach to, and structure for, ERM within the organization including roles and responsibilities
* Approving suitable internal controls and ERM policies, to ensure that ERM is being applied to the required standards, whether these standards are set internally or arise from legislation or regulation

Determining risk compensation:

* Aligning the interests of managment with investors through appropriate remuneration packages

ERM initiative needs the full backing of the Board

**Line mangers responsibilities** with regard to risk management

Implement the ERM policies agreed by the Board

* Setting up suitable risk management processes and integrating the risk information collected into business decisions

Understand the risks that they are taking and are awareof the extent of their risk taking powers

CRO is responsible for the excecution of the Board's risk management vision and strategy

### ERM and the Board

Board is responsible for the overall sucess of a company $\therefore$ responsible for ensuring the full range of risks face by the company are managed effectively

* Sucessful ERM can help the Board to discharge its responsiblities by setting the company's risk appetite
* Which then lays down the amount of risk the company is willing to take and establishing a suitable ERM framework to manage risk within the boundaries

Board has much to add directly to the ERM process:

* They have the unique opportunity to consider the risks of the company as a whole since they are at the top
* They are best placed to question and challenge corporate activities and practices

Board has influence over the success of the ERM programme through their other activities

* Board sets the direction, structure, and culture of the company and guides the allocation of financial and human resources to new initiatives

It is easy for RM to be squeezed out as viewed as low priority

Organization's employees should have codes of honesty and fair dealing

Sr mgr must lead by example to make sure the principles are honored in practice

There must be clarity in responsibilities for the idenficiation and management of risks

* Who does what, and individuals should be held accountable

Every employee has a responsibility for the identification of new and increased risk

* And should be communicated to a central point in a timely fashion

Line managers shoul be held responsible for the identification and management of risks in their own areas of responsibilities

* However the most serious strategic risks should be supervised by the Board

Board should have an annual self-assessment check to assess its progress towards full ERM

(See RBS example)

## Codes of Conduct

Development of corporate governance codes of conduct