---
title: "Module 25: Assessment of Other Risks"
author: "C. Lau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

## Module Objective

Discuss the assessment of operational, liquidity and insurance risks

***

Considering **liquidity** and **life** and **nonlife** insurance risk

14.8.5 and 14.9.1 - 14.9.3 from Sweeting is excluded

## Assessing Liquidity Risk

**Liquidity risk**:

Risk of not having sufficient `short-term` or `cash type` assets to *fund* its `short-term obligations`

* **Funding liquidity risk**:

    Risk of money markets not being able to supply funding to a business when required

    e.g. individual not able to get a mortgage when looking to buy a house due to restricted volumes of mortgage lending by banks

* **Market liquidity risk**:

    Lack of capacity in the market to handle asset transactions at the time when the deal is required (without material impact on price)

    e.g. difficulty to sell their existing house without discounting the price to make it attractive to potential buyers

Typically ***quantitative techniques are not possible*** for liquidity risk

* Historical **data** on liquidity crises is **limited**

* Degrees and **nature** of every org's **exposure** to liquidity risk is **different** (industry data may not be useful)

### Scenario Analysis

Common approach to assessing liquidity risk

***Cash inflows and outflows projection*** under a range of scenarios

* ***Cash outflows***

    * **Retail banks**
    
        **Predicting** outflow **is problematic**
  
        $\because$ Much of a bank's liabilities will be in the form of deposits from customers who may withdraw with little or no notice

    * Large mature **pension scheme**
    
        May have reasonably **predictable** cash outflows in respect of size and timing of liability payments

    * **General insurance company**
    
        May have very **unpredictable** cash outflows as both the *size* and *frequency* of the claims may be unknown

* ***Cash inflows***

    *Includes*:

    * **Revenues/income** generated by assets

        Generally can be modeled with a reasonable degree of confidence
    
    * **Potential proceeds** from the **sales** of assets

        More difficult (e.g. sale could be forced or made during time of depressed asset prices)
    
        * Much of a bank's asset based is in the form of long term mortgages that are not readily convertible into cash
    
    * **Drawing** upon **sources of liquidity**

        Maybe difficult to issue new debt or equity due to poor demand from the capital markets (result of poor credit ratings and/or business results)
    
        When modeling sources of liquidity it is important to allow for factors **limiting** the `extent` and `speed` of liquidity transfers **within** an `organization` and **between** `distinct entities`

        * Factors might be **legal**, **regulatory** or **operational** in nature
    
***Liquidity analysis***

* Once we modeled the in/outflows and sources of liquidity

    $\hookrightarrow$ Assess liquidity risk by **examining scenarios** where the **cash outflows > available cash** at future points in time

    * Important to allow for appropriate **interactions** between risks (between liquidity, market and interest rate risk)

    * Consideration should be made of both `short` and `long` term scenarios

* ***Specific scenarios*** to consider:

    1. **Rising interest rates**  

        (e.g. bank may find depositors transfer funds elsewhere in search of higher returns)
    
    2. **Rating downgrade**  

        (e.g. bank may find depositors transfer funds elsewhere in search of more secure institution)
    
    3. Large **operational loss**

        Resulting in sudden reduction in cash like asset

    4. **Large** single insurance `claim` or a `large set of claims` from associated events

        Resulting in a sudden reduction of cash assets

    5. **Loss of control** over a `key distribution channel`

        Loss of expected revenues
    
    6. **Impaired capital markets**

        Equity investors or bondholder won't be able to provide fresh capital
    
    7. Sudden **termination** of `large reinsurance contract`

        Insurer exposed to large cash outflows but without expected inflows from the reinsurance contract

### Stress Testing

Examine the effect on liquidity of an extreme event or significant change in a key assumption

(e.g. collapse of a major customer, inability to refinance a large debt that is due to mature)

The point at which scenario test becomes stress test is subjective

## Assessing Demographic Risk

Demographic risk $\in$ insurance risk

* Incl. Mortality, longevity, morbidity risk

Demographic risk

:   Arises from population changes (e.g. mortality rates) that impact on both customers and employment

Demographic risk can be broken into:

* ***Level risk*** (u/w risk):

    Risk that the particular underlying population's claims incidence and intensity is not as expected over the immediate future
    
    (e.g. due to shortcomings in the underwriting process)

* ***Reserve risk***:

    = Volatility + Cat + Trend

    * **Volatility Risk**:
    
        Uncertainty w.r.t. the **actual future immediate mortality** experience
    
        Arises due to only having a finite pool of policies
    
        $\therefore$ it is not possible to measure precisely the past underlying rates of the underlying population and going forward, the experience of sub-populations will exhibit statistical variations from that of the underlying population
    
    * **Cat Risk**:
    
        Extreme form of volatility risk (e.g. the occurrence of a natural disaster resulting a large number of deaths)
    
    * **Trend Risk** (cycle risk):
    
        Risk of future (longer term) changes in claims incidence and intensity
    
### Assessing Level Risk

Way to determine the current ***underlying level of mortality***

1. ***Experience rating***

    Involves examining the number of deaths in a portfolio of lives to determine the `inital mortality rate` or `central mortality rate`
    
    * **Initial mortality rate**:
    
        $q_x = \dfrac{d_x}{l_x}$  
    
        Applies to the number of lives at the **start of the period**
    
    * **Central mortality rate**:
    
        $m_x = \dfrac{d_x}{l_x - (d_x/2)} \approx q_x$  
        
        Applies to the **average number of lives over the period** at each age
    
2. ***Risk rating***

    Involes modeling the mortality rate of *each* `homogeneous group` as a **function of** the **shared characteristics** of their members (Model can take the form of GLM)
    
    Subsequently survivor models might be used to develop other mortality functions (e.g. $\mathring{e}_x$)
  
    **Postcode rating**: Relies on being able to identify the shared characteristics of a population from its geographic location and the there are sufficient to model the mortality of that group
  
    * Information collected from marketing and other surveys might be used
    
    * However, all memebers of the group will not necessarily conform to stereotypical risk factors upon which the model is then based
  
3. ***Combined credibility weightings***

    Combine the experience rating and risk rating methods by using a subjective credibility weighting factor $Z$ and combining the two mortality rates in proportion $Z$ and $1-Z$

Both rating methods **rely** on the data being:

* Divided into **homogeneous groups** (e.g. sex, employee type, etc)

    * Trade off between \# of groups and ensuring the sample size in each is sufficiently large

* **Collected over a period** which is sufficiently long to generate adequate data, but not so long that the mortality rates could have varied greatly

    **Credibility** vs **relevance**

### Assessing Volatility Risk

Any portfolio has a finite number of lives so there will be some statistical variation in experience

Volatility risk can be modeled probabilistically or stochastically assuming some underlying statistical process (e.g. Bin or Poisson)

The assessment process should reflect the fact that volatility risk **varies by age**

* Generally models are fitted by Poisson MLE rather than by least squares

***Poisson MLE Process***

1. Calculate the **expected number of deaths** at *each age*

    Using the model to be fitted, and set this equal to the mean of a Poisson distribution
    
2. Calculate the **probability of the observed number of deaths** at *each age*

    Based on the poisson distribution derived in step 1
    
3. **Fitted parameters** are obtained by MLE

    i.e. Product of the probabilities (for all ages) that were determined in step 2
    
### Assessing Catastrophe Risk

Risk of a sudden, temporary increase in mortality (e.g. war, pandemic)

* Best modeled using **scenario analysis**

    (e.g. scenario where there is a 20% increase in mortality at all ages)

* More complex dependencies can be modeled by **copulas**

    (e.g. consider multiple sources of mortality as separate risk factors each with their own probability distribution and then combine with copula)

Cat risk is one-way only, we can ignore the possibility of a sudden temporary reduction in mortality

### Assessing Other Demographic Risk

Other demographic factors (e.g. proportions married, \# of children etc) are less likely to vary unexpectedly

There are some other demographic risk (e.g. lapse rates or pension scheme leavers) may be more volatile

Factors that are **less likely to vary unexpectedly** can be allowed for when modeling liabilities, by **using conservative assumptions** for unknown independent variables

Other demographic risks which maybe **more significant**, are also often **dependent on other risks** (e.g. lapse increase during economic downtown)

* Such risks are best assess using **scenario analysis** (where multiple assumptions can be changed at the same time)

## Assessing Non-life Insurance Risk

Similarly can be broken into the following

* ***Level risk***:

    Dealt with the combination of experience and risk rating

* ***Reserving risk***:

    incl. `volatility`, `CAT` risk, `trend` or cycle risk

***Difference with demographic risk***

1. **Trend** (cycle) risk are more likely to correspond with **economic cycle**

    * Best assessed using **scenario analysis**

    * Non-life risk have a **shorter period of exposure**

        $\therefore$ Longer term changes in risk factors are less important than a correct assessment of the risk factors themselves

2. Non-life insurance risk can be divided based on **incidence rates**:

    * High frequency (e.g. motor)

    * Low frequency (e.g. XoL reinsurance)

3. There is the added complication of **severity** to be consider

4. Key distinction between life and non-life risk is that non-life policies may experience **more than one claim** and **move through different states over the lifetime of the policy**